e = set()
n = input("Enter the first number:- ")
e.add(int(n))
n = input("Enter the second number:- ")
e.add(int(n))
n = input("Enter the third number:- ")
e.add(int(n))
n = input("Enter the fourth number:- ")
e.add(int(n))
n = input("Enter the fifth number:- ")
e.add(int(n))
n = input("Enter the sixth number:- ")
e.add(int(n))
n = input("Enter the seventh number:- ")
e.add(int(n))
n = input("Enter the eighth number:- ")
e.add(int(n))
print(e)
